name: "Gradle build"
permissions: {}
on:
  - push

jobs:
  build:
    name: "Gradle build"
    runs-on: ubuntu-latest
    env:
      GRADLE_MICROG_VERSION_WITHOUT_GIT: 1

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"

      - name: "Setup matchers"
        run: |
          # Setting up matchers...

          matchers_dir='${{ github.workspace }}/.github/matchers'
          matcher_list()
          {
            echo 'gradle-build-matcher.json'
            echo 'gradle-build-kotlin-error-matcher.json'
          }

          matcher_list | while IFS='' read -r NAME; do
            if test -f "${matchers_dir:?}/${NAME:?}"; then
              echo "::add-matcher::${matchers_dir:?}/${NAME:?}"
              echo "Matcher configured: ${NAME:?}"
            fi
          done

      - name: "Execute Gradle assemble"
        run: "./gradlew assembleRelease"

      - name: "ls"
        run: "ls -R play-services-core/build/outputs/apk"

      # - name: "Upload APK"
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: play-services-core/build/outputs/apk/vtmDefault/release/com.google.android.gms-250932000.apk